# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dSsMXptWAZhw_OsivcRwrCzUAHvMQhoX
"""

# Import libraries
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

# Load Iris dataset
iris = load_iris()

# Create DataFrame
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['Species'] = iris.target
df['Species'] = df['Species'].replace({
    0: 'Setosa',
    1: 'Versicolor',
    2: 'Virginica'
})

# Save dataset
df.to_csv("iris.csv", index=False)

print("First 5 rows:")
print(df.head())

print("\nDataset Shape:")
print(df.shape)

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nStatistical Summary:")
print(df.describe())

# Histogram
df.hist(figsize=(10,8))
plt.savefig("histogram.png")
plt.show()

# Box Plot
df.boxplot(figsize=(10,6))
plt.savefig("boxplot.png")
plt.show()

# Scatter Plot

colors = {'Setosa':'red','Versicolor':'green','Virginica':'blue'}

plt.figure(figsize=(10, 8)) # Added for plot size control

for species in df['Species'].unique():
    subset = df[df['Species']==species]
    plt.scatter(
        subset['sepal length (cm)'],
        subset['petal length (cm)'],
        label=species,
        color=colors[species] # Using the color dictionary
    )

plt.xlabel("Sepal Length")
plt.ylabel("Petal Length")
plt.title("Scatter Plot of Sepal Length vs Petal Length by Species") # Added title for clarity
plt.legend()
plt.savefig("scatterplot.png")
plt.show()

# Correlation Heatmap

import matplotlib.pyplot as plt

corr = df.iloc[:,:4].corr()

plt.figure(figsize=(6,5))
plt.imshow(corr)

plt.xticks(range(4), corr.columns, rotation=45)
plt.yticks(range(4), corr.columns)

plt.colorbar()

plt.savefig("heatmap.png")
plt.show()

readme = """
# CodeAlpha - Data Analytics Internship

## Task 1: Exploratory Data Analysis (EDA)
This project performs Exploratory Data Analysis on the Iris dataset.

## Task 2: Data Visualization
Visualizations created:
- Histogram
- Box Plot
- Scatter Plot
- Correlation Heatmap

## Tools Used
- Python
- Pandas
- Matplotlib
- Scikit-learn

## Dataset
Iris Dataset

## Outcome
The project demonstrates how EDA and visualization help understand data.
"""

with open("README.md", "w") as f:
    f.write(readme)

    print("README.md created successfully!")